package ftsrg.rscript;

public class MirrorManager {
	private static final MirrorManager singleton = new MirrorManager();
	private String[] mirrors = {
			"http://mirror.fcaglp.unlp.edu.ar/CRAN/ - Universidad Nacional de La Plata" ,
			"http://r.mirror.mendoza-conicet.gob.ar/ - CONICET Mendoza",
			"http://cran.csiro.au/ - CSIRO",
			"http://cran.ms.unimelb.edu.au/ - University of Melbourne",
			"http://cran.at.r-project.org/ - Wirtschaftsuniversitaet Wien",
			"http://www.freestatistics.org/cran/ - K.U.Leuven Association",
			"http://cran-r.c3sl.ufpr.br/ - Universidade Federal do Parana",
			"http://cran.fiocruz.br/ - Oswaldo Cruz Foundation, Rio de Janeiro",
			"http://www.vps.fmvz.usp.br/CRAN/ - University of Sao Paulo, Sao Paulo",
			"http://brieger.esalq.usp.br/CRAN/ - University of Sao Paulo, Piracicaba",
			"http://cran.stat.sfu.ca/ - Simon Fraser University, Burnaby",
			"http://mirror.its.dal.ca/cran/ - Dalhousie University, Halifax",
			"http://probability.ca/cran/ - University of Toronto",
			"http://cran.skazkaforyou.com/ - iWeb, Montreal",
			"http://cran.parentingamerica.com/ - iWeb, Montreal",
			"http://dirichlet.mat.puc.cl/ - Pontificia Universidad Catolica de Chile, Santiago",
			"http://ftp.ctex.org/mirrors/CRAN/ - CTEX.ORG",
			"http://mirror.bjtu.edu.cn/cran/ - Beijing Jiaotong University, Beijing",
			"http://cran.dataguru.cn/ - Dataguru (a, Guangzhou",
			"http://mirrors.ustc.edu.cn/CRAN/ - University of Science and Technology of China",
			"http://mirrors.xmu.edu.cn/CRAN/ - Xiamen University",
			"http://www.laqee.unal.edu.co/CRAN/ - National University of Colombia",
			"http://www.icesi.edu.co/CRAN/ - Icesi University",
			"http://mirrors.dotsrc.org/cran/ - dotsrc.org, Aalborg",
			"http://cran.espol.edu.ec/ - Escuela Superior Politecnica del Litoral",
			"http://cran.univ-lyon1.fr/ - Dept. of Biometry & Evol. Biology, University of Lyon",
			"http://mirror.ibcp.fr/pub/CRAN/ - CNRS IBCP, Lyon",
			"http://ftp.igh.cnrs.fr/pub/CRAN/ - Institut de Genetique Humaine, Montpellier",
			"http://cran.irsn.fr/ - French Nuclear Safety Institute, Paris",
			"http://cran.univ-paris1.fr/ - Universite Paris 1 Pantheon-Sorbonne",
			"http://mirrors.softliste.de/cran/ - Softliste.de, Berlin",
			"http://cran.r-mirror.de/ - Stefan Drees, Bonn",
			"http://ftp5.gwdg.de/pub/misc/cran/ - GWDG Goettingen",
			"http://cran.cc.uoc.gr/ - University of Crete",
			"http://cran.rapporter.net/ - Rapporter.net, Budapest",
			"http://ftp.iitm.ac.in/cran/ - Indian Institute of Technology Madras",
			"http://cran.repo.bppt.go.id/ - Agency for The Application and Assessment of Technology",
			"http://cran.um.ac.ir/ - Ferdowsi University of Mashhad",
			"http://ftp.heanet.ie/mirrors/cran.r-project.org/ - HEAnet, Dublin",
			"http://cran.mirror.garr.it/mirrors/CRAN/ - Garr Mirror, Milano",
			"http://cran.stat.unipd.it/ - University of Padua",
			"http://dssm.unipa.it/CRAN/ - Universita degli Studi di Palermo",
			"http://essrc.hyogo-u.ac.jp/cran/ - Hyogo University of Teacher Education",
			"http://cran.md.tsukuba.ac.jp/ - University of Tsukuba",
			"http://cran.ism.ac.jp/ - Institute of Statistical Mathematics, Tokyo",
			"http://cran.nexr.com/ - NexR Corporation, Seoul",
			"http://biostat.cau.ac.kr/CRAN/ - Chung-Ang University, Seoul",
			"http://cran.itam.mx/ - Instituto Tecnologico Autonomo de Mexico",
			"http://www.est.colpos.mx/R-mirror/ - Colegio de Postgraduados, Texcoco",
			"http://cran.xl-mirror.nl/ - XL-Data, Amsterdam",
			"http://cran-mirror.cs.uu.nl/ - Utrecht University",
			"http://cran.stat.auckland.ac.nz/ - University of Auckland",
			"http://cran.uib.no/ - University of Bergen",
			"http://cran.stat.upd.edu.ph/ - University of the Philippines and PREGINET",
			"http://r.meteo.uni.wroc.pl/ - University of Wroclaw",
			"http://cran.dcc.fc.up.pt/ - University of Porto",
			"http://cran.gis-lab.info/ - GIS-Lab.info",
			"http://cran.stat.nus.edu.sg/ - National University of Singapore",
			"http://cran.fyxm.net/ - FYXM.net, Bratislava",
			"http://r.adu.org.za/ - University of Cape Town",
			"http://cran.mirror.ac.za/ - TENET, Johannesburg",
			"http://cran.es.r-project.org/ - Spanish National Research Network, Madrid",
			"http://ftp.sunet.se/pub/lang/CRAN/ - Swedish University Computer Network, Uppsala",
			"http://stat.ethz.ch/CRAN/ - ETH Zuerich",
			"http://cran.cs.pu.edu.tw/ - Providence University, Taichung",
			"http://cran.csie.ntu.edu.tw/ - National Taiwan University, Taipei",
			"http://mirrors.psu.ac.th/pub/cran/ - Prince of Songkla University, Hatyai",
			"http://cran.pau.edu.tr/ - Pamukkale University, Denizli",
			"http://www.stats.bris.ac.uk/R/ - University of Bristol",
			"http://cran.ma.imperial.ac.uk/ - Imperial College London",
			"http://star-www.st-andrews.ac.uk/cran/ - St Andrews University",
			"http://cran.cnr.Berkeley.edu/ - University of California, Berkeley, CA",
			"http://cran.stat.ucla.edu/ - University of California, Los Angeles, CA",
			"http://streaming.stat.iastate.edu/CRAN/ - Iowa State University, Ames, IA",
			"http://ftp.ussg.iu.edu/CRAN/ - Indiana University",
			"http://rweb.quant.ku.edu/cran/ - University of Kansas, Lawrence, KS",
			"http://watson.nci.nih.gov/cran_mirror/ - National Cancer Institute, Bethesda, MD",
			"http://cran.mtu.edu/ - Michigan Technological University, Houghton, MI",
			"http://cran.wustl.edu/ - Washington University, St. Louis, MO",
			"http://cran.case.edu/ - Case Western Reserve University, Cleveland, OH",
			"http://ftp.osuosl.org/pub/cran/ - Oregon State University",
			"http://lib.stat.cmu.edu/R/CRAN/ - Statlib, Carnegie Mellon University, Pittsburgh, PA",
			"http://cran.mirrors.hoobly.com/ - Hoobly Classifieds, Pittsburgh, PA",
			"http://mirrors.nics.utk.edu/cran/ - National Institute for Computational Sciences, Oak Ridge, TN",
			"http://cran.revolutionanalytics.com/ - Revolution Analytics, Dallas, TX",
			"http://cran.fhcrc.org/ - Fred Hutchinson Cancer Research Center, Seattle, WA",
			"http://cran.cs.wwu.edu/ - Western Washington University, Bellingham, WA",
			"http://camoruco.ing.uc.edu.ve/cran/ - Universidad de Carabobo Venezuela",
			"http://cran.vinastat.com/ - VinaStat.com",
	};
	
	private MirrorManager() {}
	
	public static MirrorManager singleton() {
		return singleton;
	}
	
	public String[] getMirrors() {
		return mirrors;
	}
}
